# Lambda functions

In [1]:
def add(a,b):
    add = a+b
    return add
add(5,3)

8

In [2]:
#Lambda functions
add = lambda a,b:a+b
add(5,3)

8

In [30]:
import pandas as pd

In [31]:
df = pd.read_csv("California Housing Test.csv")

In [32]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0

In [33]:
def increase_function(col_name):
    for i in range(len(df[col_name])):
        df[col_name][i] *=  1.1

In [24]:
increase_function('population')

/var/folders/zr/sc2knjb115gbyr8158sw0y5r0000gn/T/ipykernel_31723/966976700.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df[col_name][i] *=  1.1

# List comprehension

In [26]:
num_list = []
for each in range(10):
    num_list.append(each)
print(num_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [27]:
[n for n in range(10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [43]:
def increase_function(col_name):
    for i in range(len(df[col_name])):
        df.loc[i,col_name] *= 1.1

In [44]:
increase_function('population')
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1859.77,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,978.89,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1795.64,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,59.29,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,1028.50,237.0,2.9375,81700.0

In [29]:
def increase_function2(col_name):
    df[col_name]=[val*1.1 for val in df[col_name]]

In [31]:
increase_function2('population')

In [32]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1859.77,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,978.89,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1795.64,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,59.29,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,1028.50,237.0,2.9375,81700.0

In [49]:
def new(col):
    for i in range(len(df[col])):
        if df.loc[i,col] > 1000:
            df.loc[i,col] *= 1.1
        else:
            df.loc[i,col] *= 1.5

In [53]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0

In [54]:
new('population')

In [55]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1690.7,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,1213.5,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1632.4,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,73.5,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,1275.0,237.0,2.9375,81700.0

In [ ]:
def new(col):
    [val*1.1 if val>1000 else val*1.5 for val in df[col]]
    # [val*1.1 for val in df[col] if val>1000]
    # for i in range(len(df[col])):
    #     if df.loc[i,col] > 1000:
    #         df.loc[i,col] *= 1.1
    #     else:
    #         df.loc[i,col] *= 1.5

In [34]:
incr = lambda col_name:[val*1.1 for val in df[col_name]]

In [36]:
df['population']=incr('population')

In [37]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,2045.747,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,1076.779,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1975.204,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,65.219,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,1131.350,237.0,2.9375,81700.0

## Map

map(function,sequence)

In [5]:
def ex(v):
    return v.upper()

In [24]:
my_list = ['vedansh','bansal','python','hk']

In [12]:
for index,each in enumerate(my_list):
    # print(each,index)
    my_list[index] = ex(each)

In [13]:
my_list

['VEDANSH', 'BANSAL', 'PYTHON', 'HK']

In [18]:
num_list = [12.45,45.89,23.46]

In [21]:
list(map(int,num_list))

[12, 45, 23]

In [26]:
list(map(ex,my_list))

['VEDANSH', 'BANSAL', 'PYTHON', 'HK']

In [27]:
my_list

['vedansh', 'bansal', 'python', 'hk']

In [35]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0

In [36]:
def map_func(val):
    if val>1000:
        return val*1.1
    else:
        return val*1.5

In [38]:
df['population']=list(map(map_func,df['population']))

In [39]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1690.7,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,1213.5,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1632.4,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,73.5,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,1275.0,237.0,2.9375,81700.0

In [40]:
l = lambda val: val*1.1 if val>1000 else val*1.5
df['population']=list(map(l,df['population']))

In [41]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1859.77,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,1334.85,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1795.64,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,110.25,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,1402.50,237.0,2.9375,81700.0

In [1]:
!pip install requests

Requirement already satisfied: requests in /Users/svr/Documents/GitHub/JrMentor-Python-Projects/env/lib/python3.12/site-packages (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/svr/Documents/GitHub/JrMentor-Python-Projects/env/lib/python3.12/site-packages (from requests) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /Users/svr/Documents/GitHub/JrMentor-Python-Projects/env/lib/python3.12/site-packages (from requests) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/svr/Documents/GitHub/JrMentor-Python-Projects/env/lib/python3.12/site-packages (from requests) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in /Users/svr/Documents/GitHub/JrMentor-Python-Projects/env/lib/python3.12/site-packages (from requests) (2024.7.4)

In [2]:
import requests

In [8]:
r = requests.get('http://google.com')
# r.content

In [10]:
!pip install beautifulsoup4

Requirement already satisfied: beautifulsoup4 in /Users/svr/Documents/GitHub/JrMentor-Python-Projects/env/lib/python3.12/site-packages (4.12.3)
Requirement already satisfied: soupsieve>1.2 in /Users/svr/Documents/GitHub/JrMentor-Python-Projects/env/lib/python3.12/site-packages (from beautifulsoup4) (2.5)

In [13]:
import bs4

In [16]:
from bs4 import BeautifulSoup